export const BUG_LIST_REQUEST = 'BUG_LIST_REQUEST';
export const BUG_LIST_SUCCESS = 'BUG_LIST_SUCCESS';
export const BUG_LIST_FAIL = 'BUG_LIST_FAIL';

export const BUG_DETAILS_REQUEST = 'BUG_DETAILS_REQUEST';
export const BUG_DETAILS_SUCCESS = 'BUG_DETAILS_SUCCESS';
export const BUG_DETAILS_FAIL = 'BUG_DETAILS_FAIL';
