export const BUG_LIST_REQUEST = 'BUG_LIST_REQUEST';
export const BUG_LIST_SUCCESS = 'BUG_LIST_SUCCESS';
export const BUG_LIST_FAIL = 'BUG_LIST_FAIL';

export const BUG_DETAILS_REQUEST = 'BUG_DETAILS_REQUEST';
export const BUG_DETAILS_SUCCESS = 'BUG_DETAILS_SUCCESS';
export const BUG_DETAILS_FAIL = 'BUG_DETAILS_FAIL';

export const BUG_DELETE_REQUEST = 'BUG_DELETE_REQUEST';
export const BUG_DELETE_SUCCESS = 'BUG_DELETE_SUCCESS';
export const BUG_DELETE_FAIL = 'BUG_DELETE_FAIL';

export const BUG_CREATE_REQUEST = 'BUG_CREATE_REQUEST';
export const BUG_CREATE_SUCCESS = 'BUG_CREATE_SUCCESS';
export const BUG_CREATE_FAIL = 'BUG_CREATE_FAIL';
export const BUG_CREATE_RESET = 'BUG_CREATE_RESET';

export const BUG_UPDATE_REQUEST = 'BUG_UPDATE_REQUEST';
export const BUG_UPDATE_ASSIGNEE_SUCCESS = 'BUG_UPDATE_ASSIGNEE_SUCCESS';
export const BUG_UPDATE_NAME_SUCCESS = 'BUG_UPDATE_NAME_SUCCESS';
export const BUG_UPDATE_PROJECT_SUCCESS = 'BUG_UPDATE_PROJECT_SUCCESS';
export const BUG_UPDATE_PRIORITY_SUCCESS = 'BUG_UPDATE_PRIORITY_SUCCESS';
export const BUG_UPDATE_DUEDATE_SUCCESS = 'BUG_UPDATE_DUEDATE_SUCCESS';
export const BUG_UPDATE_DESCRIPTION_SUCCESS = 'BUG_UPDATE_DESCRIPTION_SUCCESS';
export const BUG_UPDATE_IMAGE_SUCCESS = 'BUG_UPDATE_IMAGE_SUCCESS';
export const BUG_UPDATE_COMMENT_SUCCESS = 'BUG_UPDATE_COMMENT_SUCCESS';
export const BUG_UPDATE_RESOLVED_SUCCESS = 'BUG_UPDATE_RESOLVED_SUCCESS';
export const BUG_UPDATE_FAIL = 'BUG_UPDATE_FAIL';
export const BUG_UPDATE_RESET = 'BUG_UPDATE_RESET';

export const BUG_CREATE_COMMENT_REQUEST = 'BUG_CREATE_COMMENT_REQUEST';
export const BUG_CREATE_COMMENT_SUCCESS = 'BUG_CREATE_COMMENT_SUCCESS';
export const BUG_CREATE_COMMENT_FAIL = 'BUG_CREATE_COMMENT_FAIL';
export const BUG_CREATE_COMMENT_RESET = 'BUG_CREATE_COMMENT_RESET';
