export const SCREEN_NAME_REQUEST = 'SCREEN_NAME_REQUEST';
export const SCREEN_NAME_SUCCESS = 'SCREEN_NAME_SUCCESS';
export const SCREEN_NAME_FAIL = 'SCREEN_NAME_FAIL';
export const SCREEN_NAME_RESET = 'SCREEN_NAME_RESET';

export const BUG_CREATE_PAGE = 'BUG_CREATE_PAGE';
export const BUG_EDIT_PAGE = 'BUG_EDIT_PAGE';
export const DASHBOARD_PAGE = 'DASHBOARD_PAGE';
export const USER_PROFILE_EDIT_PAGE = 'USER_PROFILE_EDIT_PAGE';
export const USER_LIST_PAGE = 'USER_LIST_PAGE';
export const USER_EDIT_PAGE = 'USER_EDIT_PAGE';
export const USER_CREATE_PAGE = 'USER_CREATE_PAGE';
export const PROJECT_LIST_PAGE = 'PROJECT_LIST_PAGE';
export const PROJECT_EDIT_PAGE = 'PROJECT_EDIT_PAGE';
export const PROJECT_CREATE_PAGE = 'PROJECT_CREATE_PAGE';
